version: "3.9"

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - instaclone-data:/mongo/db
    environment:
      MONGO_INITDB_DATABASE: instaclone

  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - instaclone-data:/redis/data

volumes:
  instaclone-data:
