version: "3.9"

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_DATABASE: instaclone

  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
